@CodingExercise_HostAddress = http://localhost:5155

POST {{CodingExercise_HostAddress}}/bank/deposit
Accept: application/json

###

POST {{CodingExercise_HostAddress}}/bank/withdrawl
Accept: application/json

###

POST {{CodingExercise_HostAddress}}/bank/withdrawl
Accept: application/json

###